Create profileMapper.py
gtadigital/ProfileMapper pull request #1
Opened 2020-09-25 13:55 UTC by ZCRNK

2020-09-25 13:55 UTC, ZCRNK commented
added python framework program

2020-10-01 05:56 UTC, matteoLorenzini requested changes

2020-10-01 05:56 UTC, matteoLorenzini commented on README.md
> + A new folder ```ProfileParser```will be created
Change ProfileParser to ProfileMapper

2020-10-01 05:56 UTC, matteoLorenzini commented on README.md
> +$ cd ProfileParser
Change ProfileParser to ProfileMapper

2020-10-01 05:56 UTC, matteoLorenzini commented on README.md
> +$ python3 profileParser.py --help
Change profileParser.py to profileMapper.py

2020-10-01 05:56 UTC, matteoLorenzini commented on README.md
> +$ python3 profileParser.py --sourcePath "your source path" --targetPath "your target path" --xslt "xslt folder"
Change profileParser.py to profileMapper.py

2020-10-01 05:56 UTC, matteoLorenzini commented on PythonFrameworkProgram/profileMapper.py
> +# author: ETH Zurich, gta digital, Matteo Lorenzini
Add Zoe Reinke as author

2020-10-03 16:08 UTC, matteoLorenzini approved these changes

2020-10-03 16:08 UTC, merged